---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

<!-- badges: Estilo da linha h1 e h2 start -->
<style>
/* Oculta a linha padrão abaixo do header de primeiro nível (#) */
h1,h2 {
    border-bottom: none !important;
}

/* Adiciona espaço (margem superior) entre o título do cabeçalho e a linha */
h1::after {
    content: "";
    display: block;
    border-bottom: 2px solid #333; /* Cor cinza escuro (#333) */
    margin-top: 20px; /* Ajuste a margem superior desejada aqui */
}

/* Estilo para a linha abaixo dos headers de segundo nível */
h2::after {
    content: "";
    display: block;
    border-bottom: 1px solid #333; /* Cor cinza escuro (#333) */
    margin-bottom: 10px; /* Espaçamento abaixo da linha */
    margin-top: 20px;
}

</style>
<!-- badges: Estilo da linha h1 e h2 end -->

<!-- <hr style="border: 1px solid #333;"> -->

## Livro Registro Parque Estatudal de Monte Alegre (PEMA)

Projeto com parcerias entre a Universidade Federal do Oeste do Pará (UFOPA) Campus de Monte Alegre, Escola Tecnológica do Estado do Pará (EETEPA) e o  Instituto de Desenvolvimento Florestal e da Biodiversidade do Estado do Pará (IDEFLOR-BIO).

### Objetivo

Desenvolver um Livro Registro digital para o PEMA.

#### Objetivos Específicos

1. Criar google forms o qual colete informações importante sobre as características do frequentadores/usuários do parque PEMA;

2. Desenvolver um banco de dados com as variáveis importantes para a administração pública do PEMA;

3. Organizar, processar e analisar os dados para transformar em informações úteis para a administração do PEMA;

4. Criar um dashboar de apresentação das informações públicas a partir dos dados do Livro Registro digital desenvolvido.

## Equipe do projeto

### Coordenadores:
* Carlos Antônio Zarzar (UFOPA - MTA);
* Anna Lins (EETEPA - Turismo);
* Jorge (IDEFLOR-BIO);

### Desenvolvedores:
* Gabriel (UFOPA)
* Luan (UFOPA)
* Daniel (UFOPA)
* EETEPA
* EETEPA
